import type { AppLocale } from "./app-locale";

/** Editör arayüzü — `getUiStrings` ile birleştirilir */
export const editorUiStrings = {
  tr: {
    editorSrTitle: "KadroKur taktik editörü",
    editorHomeAria: "Ana sayfaya dön",
    editorBrandSubtitle: "Taktik editörü",
    editorUndoRedoAria: "Geri al ve yinele",
    editorUndoTitle: "Geri al (Ctrl+Z)",
    editorUndoAria: "Geri al",
    editorRedoTitle: "Yinele (Ctrl+Shift+Z)",
    editorRedoAria: "Yinele",
    editorPitchBadgeThisPitch: "Bu sahada",
    editorUntitledTactic: "Adsız taktik",
    editorPitchAriaNoTitle: "Taktik adı henüz yok",
    editorPitchAriaWithTitle: "Bu sahada düzenlenen taktik: {title}",
    editorPanelTitle: "EDİTÖR",
    editorPanelIntro:
      "Her adımda yalnızca o bölüm açık kalır; sırayı izleyin veya aşağıdan bir başlığa tıklayın.",
    editorStepsAria: "Adımlar",
    editorStepTeam: "Takım",
    editorStepMatch: "Maç",
    editorStepOpponent: "Rakip",
    editorStepSave: "Kaydet",
    editorSectionTeam: "Takım",
    editorSectionMatch: "Maç ve diziliş",
    editorHintPlayerEdit: "Oyuncu: çift tıkla düzenle, sürükleyerek taşı.",
    editorAttackDirectionLabel: "Atak yönü (görünüm)",
    editorAttackFlipTitle:
      "Takımınız ve rakip aynı anda döner; paylaşılan linkte de bu görünüm kullanılır.",
    editorAttackDown: "↓ Aşağı atak",
    editorAttackUp: "Yukarı atak ↑",
    editorAttackLeft: "← Sola atak",
    editorAttackRight: "Sağa atak →",
    editorAttackDirectionHelp:
      "Sahayı hangi yönden görmek istediğinizi seçin. Kendi oyuncularınız ve rakip aynı anda döner; linke bakanlar da bu yönü görür.",
    editorPresetsLabel: "Hazır taktikler",
    editorResetPositions: "Oyuncu konumlarını sıfırla",
    editorSectionOpponent: "Rakip (isteğe bağlı)",
    editorOpponentFormationLabel: "Rakip dizilişi",
    editorRemove: "Kaldır",
    editorAddOpponentLineup: "Rakip dizilişi ekle",
    editorOpponentPlaceholder: "Rakip takım adı (isteğe bağlı)",
    editorOpponentAria: "Rakip takım adı",
    editorAwayPresetsLabel: "Hazır taktikler (rakip)",
    editorSectionSaveShare: "Kaydet ve paylaş",
    editorTacticNameLabel: "Taktik adı",
    editorTacticNamePlaceholder: "Taktik adını giriniz",
    editorPngSaveToGallery: "Galeriye kaydet",
    editorPngDownload: "PNG indir",
    editorShareLinkTitle: "Paylaşım linkini paylaş",
    editorShareLink: "Linki paylaş",
    editorCopyLinkTitle: "Tam paylaşım URL’sini panoya kopyala",
    editorCopyLink: "Linki kopyala",
    editorCopyClipboardTitle: "Linki panoya kopyala",
    editorCopyClipboard: "Panoya kopyala",
    editorSave: "Kaydet",
    editorTeamNameLabel: "Takım adı",
    editorTeamNamePlaceholder: "Takımınızın adını giriniz",
    editorOpponentTeamLabel: "Rakip takım",
    editorRemoveOpponent: "Rakibi kaldır",
    editorAddOpponentLineupFull: "Rakip dizilişi ekle",
    editorFormationLabel: "Diziliş",
    editorMatchTypeLabel: "Oyun tipi",
    editorSelectPlaceholder: "Seçin",
    editorPlayerEditTitle: "Oyuncu düzenle",
    editorPlayerClose: "Kapat",
    editorPlayerOpponentTeam: "Rakip takım",
    editorNameLabel: "İsim",
    editorNameHint:
      "Harf, rakam, boşluk ve . ' - (tire) kullanılabilir; özel işaret ve emoji yazılmaz.",
    editorNameErrorEmpty: "En az bir harf veya rakam girin.",
    editorRoleLabel: "Saha rolü",
    editorRoleHelp: "Konum sahada olduğu gibi kalır; rolü buradan seçebilirsiniz.",
    editorCaptainLabel: "Takım kaptanı",
    editorCaptainHelp:
      "Bu takımda yalnızca bir kaptan; başka bir oyuncuyu işaretlediğinizde aynı taraftaki önceki seçim kalkar (rakip takımda ayrı bir kaptan seçebilirsiniz).",
    editorJerseyLabel: "Forma numarası",
    editorJerseyPlaceholder: "Örn: 7",
    editorJerseyErrorRange: "1-99 arası forma numarası girin.",
    editorJerseyErrorLeadingZero: "0 ile başlayan numara kullanılamaz.",
    editorJerseyHint: "1-99 (başında 0 olmadan).",
    editorRoleKaleci: "Kaleci",
    editorRoleDefans: "Defans",
    editorRoleOrta: "Orta saha",
    editorRoleForvet: "Forvet",
    editorMobileDrawerClose: "Editör panelini kapat",
    editorMobileDrawerCloseBtn: "Kapat",
    editorMobileFabTitle: "Takım ve taktik ayarları",
    editorMobileUndoRedoAria: "Geri al ve yinele",
    editorExportFallbackFilename: "taktik",
    editorExportToastGallery: "Görsel kaydedildi. Artık stratejin cebinde! 📱",
    editorExportToastDownloaded: "Görsel indirildi.",
    editorCloudSaveToast: "Taktik başarıyla kaydedildi. Sahaya çıkmaya hazırsın! 📋",
    editorPersistenceCopyBlockedLogin: "Paylaşım linki için lütfen giriş yapın.",
    editorPersistenceCopyBlockedSaveFirst: "Paylaşım linkini kopyalamadan önce lütfen taktiği kaydedin.",
    editorPersistenceDefaultOwner: "KadroKur kullanıcısı",
    editorPersistenceLoadWarningLocal:
      "Bu kayıt bu cihazda yok. Paylaşım için yeni bir link oluşturuldu — düzenleyip Kaydet ile buluta yazın.",
    editorPersistenceLoadWarningGoogle:
      "Bu kayıt bu cihazda yok. Google ile giriş yaparsanız hesabınızdaki taktikleri de açabilirsiniz.",
    editorPersistenceNotFound: "Bu kayıt bulunamadı. Yeni taktik olarak devam edebilirsiniz.",
    editorPersistenceTitleRequired: "Lütfen önce taktik adını girin.",
    editorPersistenceSavedLocalOnly: "Kaydedildi (yalnız bu cihaz).",
    editorPersistenceSavedLocalLoginHint:
      "Kaydedildi (yalnız bu cihaz). Diğer cihazlarda görmek için giriş yapıp tekrar kaydedin.",
    editorPersistenceSavedLocalCloudFail:
      "Bu cihazda kaydedildi; buluta yazılamadı. Bağlantınızı ve oturumunuzu kontrol edip yeniden deneyin.",
    editorPersistenceSavedDevice: "Taktik bu cihazda kaydedildi.",
    editorPersistenceSaveError: "Kaydedilirken bir hata oluştu. Lütfen tekrar deneyin.",
    editorPersistenceLinkCopied: "Link panoya kopyalandı.",
    editorPersistenceShareNeedSave: "Paylaşım linkini paylaşmadan önce lütfen taktiği kaydedin.",
    editorPersistenceShareTitle: "KadroKur taktik",
    editorPersistenceShareText: "Taktik paylaşım linki:",
    editorPersistenceShareSuccess: "Taktik başarıyla paylaşıldı! Maç toplantısına hazırsın. 🏟️",
    editorMatch_5v5: "5 Kişilik",
    editorMatch_6v6: "6 Kişilik",
    editorMatch_7v7: "7 Kişilik",
    editorMatch_8v8: "8 Kişilik",
    editorMatch_9v9: "9 Kişilik",
    editorMatch_10v10: "10 Kişilik",
    editorMatch_11v11: "11 Kişilik",
    editorPreset_default: "Standart",
    editorPreset_press: "Yüksek pres",
    editorPreset_counter: "Kontra",
    editorPreset_possession: "Topa sahip olma",
    editorPreset_low_block: "Düşük blok",
    editorPlayerFallbackPrefix: "Oyuncu",
  },
  en: {
    editorSrTitle: "KadroKur tactics editor",
    editorHomeAria: "Back to home",
    editorBrandSubtitle: "Tactics editor",
    editorUndoRedoAria: "Undo and redo",
    editorUndoTitle: "Undo (Ctrl+Z)",
    editorUndoAria: "Undo",
    editorRedoTitle: "Redo (Ctrl+Shift+Z)",
    editorRedoAria: "Redo",
    editorPitchBadgeThisPitch: "On this pitch",
    editorUntitledTactic: "Untitled tactic",
    editorPitchAriaNoTitle: "No tactic name yet",
    editorPitchAriaWithTitle: "Tactic edited on this pitch: {title}",
    editorPanelTitle: "EDITOR",
    editorPanelIntro:
      "Only one section stays open at a time; follow the steps or tap a heading below.",
    editorStepsAria: "Steps",
    editorStepTeam: "Team",
    editorStepMatch: "Match",
    editorStepOpponent: "Opponent",
    editorStepSave: "Save",
    editorSectionTeam: "Team",
    editorSectionMatch: "Match & formation",
    editorHintPlayerEdit: "Player: double-tap to edit, drag to move.",
    editorAttackDirectionLabel: "Attack direction (view)",
    editorAttackFlipTitle:
      "Your team and the opponent rotate together; shared links use this view too.",
    editorAttackDown: "↓ Attack down",
    editorAttackUp: "Attack up ↑",
    editorAttackLeft: "← Attack left",
    editorAttackRight: "Attack right →",
    editorAttackDirectionHelp:
      "Choose how you want to see the pitch. Your players and the opponent rotate together; anyone opening the link sees the same orientation.",
    editorPresetsLabel: "Quick tactics",
    editorResetPositions: "Reset player positions",
    editorSectionOpponent: "Opponent (optional)",
    editorOpponentFormationLabel: "Opponent formation",
    editorRemove: "Remove",
    editorAddOpponentLineup: "Add opponent lineup",
    editorOpponentPlaceholder: "Opponent team name (optional)",
    editorOpponentAria: "Opponent team name",
    editorAwayPresetsLabel: "Quick tactics (opponent)",
    editorSectionSaveShare: "Save & share",
    editorTacticNameLabel: "Tactic name",
    editorTacticNamePlaceholder: "Enter tactic name",
    editorPngSaveToGallery: "Save to gallery",
    editorPngDownload: "Download PNG",
    editorShareLinkTitle: "Share link",
    editorShareLink: "Share link",
    editorCopyLinkTitle: "Copy full share URL to clipboard",
    editorCopyLink: "Copy link",
    editorCopyClipboardTitle: "Copy link to clipboard",
    editorCopyClipboard: "Copy to clipboard",
    editorSave: "Save",
    editorTeamNameLabel: "Team name",
    editorTeamNamePlaceholder: "Enter your team name",
    editorOpponentTeamLabel: "Opponent",
    editorRemoveOpponent: "Remove opponent",
    editorAddOpponentLineupFull: "Add opponent lineup",
    editorFormationLabel: "Formation",
    editorMatchTypeLabel: "Match type",
    editorSelectPlaceholder: "Select",
    editorPlayerEditTitle: "Edit player",
    editorPlayerClose: "Close",
    editorPlayerOpponentTeam: "Opponent team",
    editorNameLabel: "Name",
    editorNameHint:
      "Letters, numbers, spaces and . ' - (hyphen) allowed; no special symbols or emoji.",
    editorNameErrorEmpty: "Enter at least one letter or number.",
    editorRoleLabel: "Role",
    editorRoleHelp: "Position on the pitch stays the same; pick the role here.",
    editorCaptainLabel: "Team captain",
    editorCaptainHelp:
      "Only one captain per side; choosing another player clears the previous pick on that side (you can set a separate captain for the opponent).",
    editorJerseyLabel: "Shirt number",
    editorJerseyPlaceholder: "e.g. 7",
    editorJerseyErrorRange: "Enter a number between 1 and 99.",
    editorJerseyErrorLeadingZero: "Numbers cannot start with 0.",
    editorJerseyHint: "1–99 (no leading zero).",
    editorRoleKaleci: "Goalkeeper",
    editorRoleDefans: "Defence",
    editorRoleOrta: "Midfield",
    editorRoleForvet: "Forward",
    editorMobileDrawerClose: "Close editor panel",
    editorMobileDrawerCloseBtn: "Close",
    editorMobileFabTitle: "Team & tactic settings",
    editorMobileUndoRedoAria: "Undo and redo",
    editorExportFallbackFilename: "tactic",
    editorExportToastGallery: "Image saved. Your strategy fits in your pocket! 📱",
    editorExportToastDownloaded: "Image downloaded.",
    editorCloudSaveToast: "Tactic saved. You’re ready to hit the pitch! 📋",
    editorPersistenceCopyBlockedLogin: "Sign in to get a share link.",
    editorPersistenceCopyBlockedSaveFirst: "Save the tactic before copying the share link.",
    editorPersistenceDefaultOwner: "KadroKur user",
    editorPersistenceLoadWarningLocal:
      "This save isn’t on this device. A new share link was created — edit and Save to sync to the cloud.",
    editorPersistenceLoadWarningGoogle:
      "This save isn’t on this device. Sign in with Google to open tactics from your account.",
    editorPersistenceNotFound: "This tactic wasn’t found. You can continue with a new one.",
    editorPersistenceTitleRequired: "Please enter a tactic name first.",
    editorPersistenceSavedLocalOnly: "Saved (this device only).",
    editorPersistenceSavedLocalLoginHint:
      "Saved (this device only). Sign in and save again to see it on other devices.",
    editorPersistenceSavedLocalCloudFail:
      "Saved on this device; cloud sync failed. Check your connection and session, then try again.",
    editorPersistenceSavedDevice: "Tactic saved on this device.",
    editorPersistenceSaveError: "Something went wrong while saving. Please try again.",
    editorPersistenceLinkCopied: "Link copied to clipboard.",
    editorPersistenceShareNeedSave: "Save the tactic before sharing the link.",
    editorPersistenceShareTitle: "KadroKur tactic",
    editorPersistenceShareText: "Tactic share link:",
    editorPersistenceShareSuccess: "Shared successfully! Ready for the match briefing. 🏟️",
    editorMatch_5v5: "5-a-side",
    editorMatch_6v6: "6-a-side",
    editorMatch_7v7: "7-a-side",
    editorMatch_8v8: "8-a-side",
    editorMatch_9v9: "9-a-side",
    editorMatch_10v10: "10-a-side",
    editorMatch_11v11: "11-a-side",
    editorPreset_default: "Standard",
    editorPreset_press: "High press",
    editorPreset_counter: "Counter",
    editorPreset_possession: "Possession",
    editorPreset_low_block: "Low block",
    editorPlayerFallbackPrefix: "Player",
  },
} as const;

export type EditorUiStrings = (typeof editorUiStrings)[AppLocale];
