import type { AppLocale } from "./app-locale";

/** Kullanıcı paneli + Taktiklerim — `getUiStrings` ile birleştirilir */
export const panelUiStrings = {
  tr: {
    panelDefaultDisplayName: "Hesabım",
    panelNavProfile: "Profil",
    panelNavPersonal: "Kişisel Bilgiler",
    panelNavSettings: "Ayarlar",
    panelEditProfileHint: "Profilini düzenle",
    panelNavSection: "Gezinme",
    panelNavAria: "Kullanıcı paneli menüsü",
    panelBackHome: "Ana sayfaya dön",
    panelMenuOpenMobile: "Menüyü aç",
    panelMenuCloseMobile: "Menüyü kapat",
    panelLoadingMessage: "Kullanıcı paneli hazırlanıyor...",

    panelSave: "Kaydet",
    panelSaving: "Kaydediliyor...",
    panelFooterShieldProfile:
      "Verilerin yalnızca hesabına bağlıdır; dilediğinde güncelleyebilirsin.",
    panelFooterShieldPersonal: "Bu bilgiler yalnızca senin hesabına bağlıdır.",

    panelProfileSaved: "Profil bilgileriniz kaydedildi.",
    panelProfileRateLimit: "Çok hızlı işlem yapıyorsunuz. Lütfen birkaç saniye bekleyip tekrar deneyin.",
    panelProfileSaveErrorPrefix: "Profil kaydedilirken bir hata oluştu.",
    panelProfileSaveErrorRetry: "Lütfen tekrar deneyin.",
    panelProfileSaveErrorDetail: "Detay:",

    panelProfileEyebrow: "Futbol profili",
    panelProfileTitle: "Profil",
    panelProfileIntro:
      "Saha tercihlerin ve görünürlük ayarların tek yerde. Kaydettiğinde taktik paylaşımlarında da kullanılır.",
    panelSectionPitchRole: "Saha & rol",
    panelSectionPitchRoleDesc:
      "Takımın, oynadığın bölge ve ayak tercihin — editör ve kartlarda özet olarak görünebilir.",
    panelFavoriteTeam: "Tuttuğu takım",
    panelFavoriteTeamPlaceholder: "Örn: Yeşil forma",
    panelPosition: "Pozisyon",
    panelSelectPlaceholder: "Seçiniz",
    panelPositionGk: "Kaleci",
    panelPositionDef: "Defans",
    panelPositionMid: "Orta Saha",
    panelPositionFwd: "Forvet",
    panelPreferredFoot: "Tercih edilen ayak",
    panelFootRight: "Sağ",
    panelFootLeft: "Sol",
    panelFootBoth: "İki Ayak",
    panelDominantRoles: "Baskın roller",
    panelDominantRolesHint: "Virgülle ayırın — örn: oyun kurucu, presçi",
    panelDominantRolesPlaceholder: "Örn: Oyun kurucu, Presçi, Bitirici",
    panelSectionLocation: "Konum",
    panelSectionLocationDesc:
      "Şehir ve ilçe bilgini ekleyerek, yakındaki takımlarla ve oyuncularla eşleşmeye bir adım daha yaklaşabilirsin.",
    panelSectionVisibility: "Görünürlük & iletişim",
    panelSectionVisibilityDesc:
      "Profil fotoğrafı linki ve sosyal hesabın; gizlilik kimin seni görebileceğini belirler.",
    panelAvatarUrl: "Avatar URL",
    panelAvatarUrlHint: "Kare veya yuvarlak görsel önerilir (HTTPS)",
    panelSocialLink: "Instagram / sosyal link",
    panelPrivacyLevel: "Gizlilik seviyesi",
    panelPrivacyPublic: "Herkese açık",
    panelPrivacyFriends: "Sadece arkadaşlar",
    panelPrivacyPrivate: "Gizli",

    panelPersonalEyebrow: "Hesap",
    panelPersonalTitle: "Kişisel bilgiler",
    panelPersonalIntro:
      "Adın, iletişimin ve fiziksel bilgilerin; kadro ve profil kartlarında kullanılabilir.",
    panelSectionIdentity: "Kimlik",
    panelSectionIdentityDesc: "Kayıtta kullandığın isim bilgileri; istersen buradan güncelleyebilirsin.",
    panelFirstName: "Ad",
    panelFirstNamePlaceholder: "Adın",
    panelLastName: "Soyad",
    panelLastNamePlaceholder: "Soyadın",
    panelSectionBio: "Kendini anlat",
    panelSectionBioDesc:
      "Kısa bir tanıtım; topluluk özelliklerinde veya ileride profil önizlemesinde görünebilir.",
    panelBio: "Kısa biyografi",
    panelBioPlaceholder: "Halı saha tarzın, oynadığın lig veya kısa bir not...",
    panelSectionContact: "İletişim",
    panelSectionContactDesc: "Telefon isteğe bağlıdır; etkinlik veya ekip bildirimleri için kullanılabilir.",
    panelPhone: "Telefon",
    panelPhoneOptional: "Opsiyonel",
    panelPhonePlaceholder: "+90 5xx xxx xx xx",
    panelSectionPhysical: "Fiziksel Detaylar",
    panelSectionPhysicalDesc:
      "Doğum tarihi yaşını otomatik hesaplar; boy ve kilo istatistik veya kadro önerileri için kullanılabilir.",
    panelBirthDate: "Doğum tarihi",
    panelAge: "Yaş",
    panelAgeFromBirth: "(Doğum tarihinden hesaplanır)",
    panelHeightCm: "Boy (cm)",
    panelHeightPlaceholder: "Örn: 178",
    panelWeightKg: "Kilo (kg)",
    panelWeightPlaceholder: "Örn: 72",

    panelSettingsTitle: "Ayarlar",
    panelSettingsSession: "Oturum:",
    panelSettingsUnknown: "Bilinmiyor",
    panelSettingsComingSoon:
      "Yakında: hesap ayarları ve tercihlerinizi buradan yönetebileceksiniz.",

    panelLocationCity: "Şehir",
    panelLocationDistrict: "İlçe",
    panelLocationSelectCity: "Şehir seçin",
    panelLocationSelectDistrict: "İlçe seçin",
    panelLocationSelectCityFirst: "Önce şehir seçin",
    panelLocationPickCityFirst: "Lütfen önce şehir seçiniz",

    myTacticsTitle: "Taktiklerim",
    myTacticsNew: "Yeni Taktik Oluştur",
    myTacticsLoadError: "Taktikler yüklenirken bir hata oluştu.",
    myTacticsEmptyTitle: "Henüz bir taktiğin yok",
    myTacticsEmptyHint: "İlk taktiğini oluşturmak için editöre geçebilirsin.",
    myTacticsShareNeedPublic: "Önce taktiği herkese açık yapmalısın",
    myTacticsCopySuccess: "Bağlantı kopyalandı!",
    myTacticsCopyFail: "Bağlantı kopyalanamadı. Lütfen tekrar deneyin.",
    myTacticsShareSuccessToast: "Taktik başarıyla paylaşıldı! Maç toplantısına hazırsın. 🏟️",
    myTacticsNoCanvasData: "Taktik verisi bulunamadı.",
    myTacticsShareImageTitle: "Taktik Paylaşımı",
    myTacticsShareImageText: "Taktik görselime göz at! Kendi taktiğini oluşturmak için:",
    myTacticsShareMenuOpened: "Paylaşım menüsü açıldı",
    myTacticsDownloadedClipboardOk: "Görsel indirildi; metin ve taktik linki panoya kopyalandı.",
    myTacticsDownloadedCopyLinkHint: "Görsel indirildi. Linki aşağıdaki kutudan kopyalayabilirsin.",
    myTacticsImageShareFail: "Görsel oluşturulamadı veya paylaşılamadı.",
    myTacticsPngGallery: "Görsel kaydedildi. Artık stratejin cebinde! 📱",
    myTacticsPngDownloaded: "Görsel indirildi.",
    myTacticsPngFail: "Görsel oluşturulamadı",
    myTacticsDeleteForbidden: "Yetki Hatası: Bu taktik hesabınıza bağlı olmadığı için silinemedi.",
    myTacticsDeleted: "Başarıyla Silindi",
    myTacticsDeleteError: "Taktik silinirken bir hata oluştu. Lütfen tekrar deneyin.",
    myTacticsDeleteModalTitle: "Taktiği Sil",
    myTacticsDeleteModalDesc: "kalıcı olarak silinecek. Bu işlemi geri alamazsın.",
    myTacticsDeleteModalFallbackName: "Bu taktik",
    myTacticsCancel: "Vazgeç",
    myTacticsDeleteConfirm: "Taktiği Sil",
    myTacticsDeleting: "Siliniyor...",
    myTacticsShareSheetTitle: "Paylaş",
    myTacticsShareImageBtn: "Görseli Paylaş / Kaydet",
    myTacticsPreparing: "Hazırlanıyor...",
    myTacticsSaving: "Kaydediliyor...",
    myTacticsDownloading: "İndiriliyor...",
    myTacticsGallerySave: "Galeriye kaydet",
    myTacticsDownloadImage: "Görseli İndir",
    myTacticsNoShareLink: "Paylaşım linki yok",
    myTacticsShareLinkTitle: "Paylaşım linkini paylaş",
    myTacticsCopyClipboardTitle: "Panoya kopyala",
    myTacticsCopyLinkDesktop: "Linki kopyala",
    myTacticsShareLinkShort: "Linki paylaş",
    myTacticsCopyClipboardShort: "Panoya kopyala",

    tacticUntitled: "İsimsiz Taktik",
    tacticEdit: "Düzenle",
    tacticDeleteAria: "Taktiği sil",
    tacticShareAria: "Paylaşım panelini aç",
    tacticShareTitle: "Paylaşım panelini aç",
    tacticCreatedTooltip: "Oluşturulma: {date}",
    tacticCreatedUnknown: "Oluşturulma tarihi bilinmiyor",
    tacticFilenameFallback: "taktik",
  },
  en: {
    panelDefaultDisplayName: "My account",
    panelNavProfile: "Profile",
    panelNavPersonal: "Personal info",
    panelNavSettings: "Settings",
    panelEditProfileHint: "Edit your profile",
    panelNavSection: "Navigation",
    panelNavAria: "User panel menu",
    panelBackHome: "Back to home",
    panelMenuOpenMobile: "Open menu",
    panelMenuCloseMobile: "Close menu",
    panelLoadingMessage: "Loading user panel...",

    panelSave: "Save",
    panelSaving: "Saving...",
    panelFooterShieldProfile:
      "Your data is tied to your account only; you can update it anytime.",
    panelFooterShieldPersonal: "This information is tied to your account only.",

    panelProfileSaved: "Your profile has been saved.",
    panelProfileRateLimit: "You’re going too fast. Please wait a few seconds and try again.",
    panelProfileSaveErrorPrefix: "Something went wrong while saving your profile.",
    panelProfileSaveErrorRetry: "Please try again.",
    panelProfileSaveErrorDetail: "Detail:",

    panelProfileEyebrow: "Football profile",
    panelProfileTitle: "Profile",
    panelProfileIntro:
      "Your pitch preferences and visibility in one place. Saved data is also used when you share tactics.",
    panelSectionPitchRole: "Pitch & role",
    panelSectionPitchRoleDesc:
      "Your team, position, and foot preference — may appear as a summary in the editor and cards.",
    panelFavoriteTeam: "Favorite team",
    panelFavoriteTeamPlaceholder: "e.g. Green kit",
    panelPosition: "Position",
    panelSelectPlaceholder: "Select",
    panelPositionGk: "Goalkeeper",
    panelPositionDef: "Defence",
    panelPositionMid: "Midfield",
    panelPositionFwd: "Forward",
    panelPreferredFoot: "Preferred foot",
    panelFootRight: "Right",
    panelFootLeft: "Left",
    panelFootBoth: "Both feet",
    panelDominantRoles: "Main roles",
    panelDominantRolesHint: "Comma-separated — e.g. playmaker, presser",
    panelDominantRolesPlaceholder: "e.g. Playmaker, Presser, Finisher",
    panelSectionLocation: "Location",
    panelSectionLocationDesc:
      "Add your city and district to get one step closer to matching with nearby teams and players.",
    panelSectionVisibility: "Visibility & contact",
    panelSectionVisibilityDesc:
      "Profile photo URL and social link; privacy controls who can see you.",
    panelAvatarUrl: "Avatar URL",
    panelAvatarUrlHint: "Square or round image recommended (HTTPS)",
    panelSocialLink: "Instagram / social link",
    panelPrivacyLevel: "Privacy level",
    panelPrivacyPublic: "Public",
    panelPrivacyFriends: "Friends only",
    panelPrivacyPrivate: "Private",

    panelPersonalEyebrow: "Account",
    panelPersonalTitle: "Personal information",
    panelPersonalIntro:
      "Your name, contact, and physical details; can be used in squad and profile cards.",
    panelSectionIdentity: "Identity",
    panelSectionIdentityDesc: "The name you used to register; you can update it here.",
    panelFirstName: "First name",
    panelFirstNamePlaceholder: "Your first name",
    panelLastName: "Last name",
    panelLastNamePlaceholder: "Your last name",
    panelSectionBio: "About you",
    panelSectionBioDesc:
      "A short intro; may appear in community features or future profile previews.",
    panelBio: "Short bio",
    panelBioPlaceholder: "Your style, league, or a short note...",
    panelSectionContact: "Contact",
    panelSectionContactDesc: "Phone is optional; may be used for events or team notifications.",
    panelPhone: "Phone",
    panelPhoneOptional: "Optional",
    panelPhonePlaceholder: "+1 …",
    panelSectionPhysical: "Physical details",
    panelSectionPhysicalDesc:
      "Birth date calculates your age; height and weight can be used for stats or squad suggestions.",
    panelBirthDate: "Date of birth",
    panelAge: "Age",
    panelAgeFromBirth: "(Calculated from date of birth)",
    panelHeightCm: "Height (cm)",
    panelHeightPlaceholder: "e.g. 178",
    panelWeightKg: "Weight (kg)",
    panelWeightPlaceholder: "e.g. 72",

    panelSettingsTitle: "Settings",
    panelSettingsSession: "Session:",
    panelSettingsUnknown: "Unknown",
    panelSettingsComingSoon:
      "Coming soon: manage account settings and preferences here.",

    panelLocationCity: "City",
    panelLocationDistrict: "District",
    panelLocationSelectCity: "Select city",
    panelLocationSelectDistrict: "Select district",
    panelLocationSelectCityFirst: "Select city first",
    panelLocationPickCityFirst: "Please select a city first",

    myTacticsTitle: "My tactics",
    myTacticsNew: "Create new tactic",
    myTacticsLoadError: "Could not load tactics.",
    myTacticsEmptyTitle: "No tactics yet",
    myTacticsEmptyHint: "Open the editor to create your first tactic.",
    myTacticsShareNeedPublic: "Make the tactic public first",
    myTacticsCopySuccess: "Link copied!",
    myTacticsCopyFail: "Could not copy the link. Please try again.",
    myTacticsShareSuccessToast: "Shared successfully! Ready for the match briefing. 🏟️",
    myTacticsNoCanvasData: "Tactic data not found.",
    myTacticsShareImageTitle: "Tactic share",
    myTacticsShareImageText: "Check out my tactic image! Create yours at:",
    myTacticsShareMenuOpened: "Share sheet opened",
    myTacticsDownloadedClipboardOk: "Image downloaded; text and link copied to clipboard.",
    myTacticsDownloadedCopyLinkHint: "Image downloaded. Copy the link from the field below.",
    myTacticsImageShareFail: "Could not create or share the image.",
    myTacticsPngGallery: "Image saved. Your strategy fits in your pocket! 📱",
    myTacticsPngDownloaded: "Image downloaded.",
    myTacticsPngFail: "Could not create image",
    myTacticsDeleteForbidden: "Permission denied: this tactic isn’t linked to your account.",
    myTacticsDeleted: "Deleted",
    myTacticsDeleteError: "Could not delete the tactic. Please try again.",
    myTacticsDeleteModalTitle: "Delete tactic",
    myTacticsDeleteModalDesc: "will be permanently deleted. You can’t undo this.",
    myTacticsDeleteModalFallbackName: "This tactic",
    myTacticsCancel: "Cancel",
    myTacticsDeleteConfirm: "Delete tactic",
    myTacticsDeleting: "Deleting...",
    myTacticsShareSheetTitle: "Share",
    myTacticsShareImageBtn: "Share / save image",
    myTacticsPreparing: "Preparing...",
    myTacticsSaving: "Saving...",
    myTacticsDownloading: "Downloading...",
    myTacticsGallerySave: "Save to gallery",
    myTacticsDownloadImage: "Download image",
    myTacticsNoShareLink: "No share link",
    myTacticsShareLinkTitle: "Share link",
    myTacticsCopyClipboardTitle: "Copy to clipboard",
    myTacticsCopyLinkDesktop: "Copy link",
    myTacticsShareLinkShort: "Share link",
    myTacticsCopyClipboardShort: "Copy to clipboard",

    tacticUntitled: "Untitled tactic",
    tacticEdit: "Edit",
    tacticDeleteAria: "Delete tactic",
    tacticShareAria: "Open share panel",
    tacticShareTitle: "Open share panel",
    tacticCreatedTooltip: "Created: {date}",
    tacticCreatedUnknown: "Created date unknown",
    tacticFilenameFallback: "tactic",
  },
} as const;

export type PanelUiStrings = (typeof panelUiStrings)[AppLocale];
